CREATE TYPE ticket_status   AS ENUM ('OPEN','IN_PROGRESS','WAITING_CUSTOMER',
                                     'RESOLVED','CLOSED','CANCELLED');
CREATE TYPE ticket_priority AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');


CREATE TABLE ticket_categories (
    id     SMALLINT    GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR(60) NOT NULL,
    slug   VARCHAR(60) NOT NULL,
    active BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_ticket_categories      PRIMARY KEY (id),
    CONSTRAINT uk_ticket_categories_name UNIQUE (name),
    CONSTRAINT uk_ticket_categories_slug UNIQUE (slug),
    CONSTRAINT ck_ticket_categories_slug CHECK (slug ~ '^[a-z0-9-]+$')
);

CREATE SEQUENCE ticket_number_seq AS BIGINT START WITH 1 INCREMENT BY 1;


CREATE TABLE tickets (
    id                UUID            NOT NULL,
    ticket_number     BIGINT          NOT NULL DEFAULT nextval('ticket_number_seq'),

    customer_id       UUID            NOT NULL,
    category_id       SMALLINT        NOT NULL,

    status            ticket_status   NOT NULL DEFAULT 'OPEN',
    priority          ticket_priority NOT NULL DEFAULT 'MEDIUM',

    title             VARCHAR(160)    NOT NULL,
    description       TEXT,

    created_by        UUID            NOT NULL,
    assigned_to       UUID,

    opened_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),
    first_response_at TIMESTAMPTZ,
    resolved_at       TIMESTAMPTZ,
    closed_at         TIMESTAMPTZ,

    created_at        TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ     NOT NULL DEFAULT now(),
    version           BIGINT          NOT NULL DEFAULT 0,

    CONSTRAINT pk_tickets              PRIMARY KEY (id),
    CONSTRAINT uk_tickets_number       UNIQUE (ticket_number),
    CONSTRAINT fk_tickets_customer     FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_tickets_category     FOREIGN KEY (category_id) REFERENCES ticket_categories (id),
    CONSTRAINT fk_tickets_created_by   FOREIGN KEY (created_by)  REFERENCES users (id),
    CONSTRAINT fk_tickets_assigned_to  FOREIGN KEY (assigned_to) REFERENCES users (id),
    CONSTRAINT ck_tickets_title_filled CHECK (length(btrim(title)) > 0)
);

COMMENT ON COLUMN tickets.created_by IS
    'Autor original. Imutavel apos a criacao (corrige B2).';


CREATE TABLE ticket_comments (
    id            UUID        NOT NULL,
    ticket_id     UUID        NOT NULL,
    author_id     UUID        NOT NULL,
    body          TEXT        NOT NULL,
    internal_note BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_ticket_comments        PRIMARY KEY (id),
    CONSTRAINT fk_ticket_comments_ticket FOREIGN KEY (ticket_id)
        REFERENCES tickets (id) ON DELETE CASCADE,
    CONSTRAINT fk_ticket_comments_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT ck_ticket_comments_body   CHECK (length(btrim(body)) > 0)
);


CREATE TABLE ticket_status_history (
    id          UUID          NOT NULL,
    ticket_id   UUID          NOT NULL,
    from_status ticket_status,
    to_status   ticket_status NOT NULL,
    changed_by  UUID          NOT NULL,
    reason      TEXT,
    changed_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT pk_ticket_status_history        PRIMARY KEY (id),
    -- Sem ON DELETE CASCADE: e uma trilha de auditoria. Tickets nunca sao
    -- eliminados (passam a CANCELLED), logo isto protege o historico de um
    -- DELETE acidental em vez de o apagar em silencio.
    CONSTRAINT fk_ticket_status_history_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_ticket_status_history_user   FOREIGN KEY (changed_by) REFERENCES users (id),
    CONSTRAINT ck_ticket_status_history_change CHECK (from_status IS DISTINCT FROM to_status)
);


CREATE TABLE attachments (
    id           UUID         NOT NULL,
    ticket_id    UUID         NOT NULL,
    uploaded_by  UUID         NOT NULL,
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    storage_key  VARCHAR(512) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_attachments             PRIMARY KEY (id),
    CONSTRAINT uk_attachments_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_attachments_ticket      FOREIGN KEY (ticket_id)
        REFERENCES tickets (id) ON DELETE CASCADE,
    CONSTRAINT fk_attachments_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id),
    CONSTRAINT ck_attachments_size        CHECK (size_bytes > 0)
);
